# Generated by Django 5.2 on 2025-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_slot',
            field=models.CharField(choices=[('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00')], default='09:00-10:00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_info',
            field=models.CharField(default=6238934854, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='service_mode',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='Watsapp', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
