# Generated by Django 5.2 on 2025-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_id'),
        ('booking', '0003_booking_booking_id'),
    ]

    operations = [
    ]
