# Generated by Django 5.2 on 2025-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_0003_alter_booking_id_0003_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_mode',
        ),
        migrations.AddField(
            model_name='booking',
            name='email_info',
            field=models.EmailField(default='ashwin@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
